language: node_js

sudo: required

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - docker-compose up --no-start build
  - docker-compose run build bash -c "yarn install --ignore-engines"

install: true # to avoid the default install step

script:
  - docker-compose run build bash -c "yarn lint"

deploy:
  - provider: script
    skip_cleanup: true
    script: docker-compose run build bash -c "yarn deploy:prod"
    on:
      branch:
        - master
